services:
  db:
    image: postgres:17.2
    restart: always
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_USER: admin
      POSTGRES_DB: db
    volumes:
      - pgdata:/var/lib/postgresql/data 
    ports:
      - "5332:5432"
 
volumes:
  pgdata: